// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fboxwvycbohjdynjkjdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZib3h3dnljYm9oamR5bmpramR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTg5NzgsImV4cCI6MjA3MTMzNDk3OH0.Wpy1K2kbhyPY6QuoVgBKGfukzh_NHP_Z0ABtDVeZvOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});